export const projects = [
	{
		title: 'Game Store',
		description: "",
		image: '/images/1.png',
		tags: ['React', "Redux", 'Node', 'Express', "MVC", 'TailWind'],
		source: 'https://game-redux.herokuapp.com/',
		visit: 'https://github.com/Lyshka/game-store-redux',
		id: 0,
	},
	{
		title: 'Tik Tok Lyshka',
		description: "",
		image: '/images/2.png',
		tags: ['React', "TypeScript", 'Next', "Sanity", "GoogleAuth", "TailWind"],
		source: 'https://tic-tok-lyshka.vercel.app/',
		visit: 'https://github.com/Lyshka/tik-tok-lyshka',
		id: 1,
	},
	{
		title: 'Chess Lyshka',
		description: "",
		image: '/images/3.jpg',
		tags: ['React'],
		source: 'https://superlative-frangipane-1db274.netlify.app/',
		visit: 'https://github.com/Lyshka/react-chess-master',
		id: 2,
	},
	{
		title: 'Pinterest Lyshka',
		description: "",
		image: '/images/4.jpg',
		tags: ['React', 'Sanity', "GoogleAuth", 'TailWind'],
		source: 'https://fancy-sunflower-fe4ca3.netlify.app/',
		visit: 'https://github.com/Lyshka/pinterest-lyshka',
		id: 3,
	},
	{
		title: 'Google Calendar Lyshka',
		description: "",
		image: '/images/5.jpg',
		tags: ['React', "LocalStorage", 'TailWind'],
		source: 'https://main--amazing-marigold-531483.netlify.app/',
		visit: 'https://github.com/Lyshka/google-calendar',
		id: 4,
	},
	{
		title: 'Search Google Lyshka',
		description: "",
		image: '/images/6.jpg',
		tags: ['React', "API JSON", 'TailWind'],
		source: 'https://search-lyshka.herokuapp.com/',
		visit: 'https://github.com/Lyshka/search-google-lyshka',
		id: 5,
	},
	{
		title: 'VideoTube Lyshka',
		description: "",
		image: '/images/7.jpg',
		tags: ['React', "API JSON", 'Material UI'],
		source: 'https://idyllic-tanuki-a72fbc.netlify.app/',
		visit: 'https://github.com/Lyshka/videotube-lyshka',
		id: 6,
	},
	{
		title: 'YouTube Clone Lyshka',
		description: "",
		image: '/images/8.jpg',
		tags: ['React', "Redux", "Node", "MongoDB", "Firebase", 'Styled Component'],
		source: 'https://bright-belekoy-1cdafd.netlify.app/',
		visit: 'https://github.com/Lyshka/youtube-clone',
		id: 7,
	},
	{
		title: 'Showcase NFT App',
		description: "",
		image: '/images/9.jpg',
		tags: ['React-Native', "MOCK JSON", 'Styled Component'],
		source: 'https://late-glade-3156.on.fleek.co/',
		visit: 'https://github.com/Lyshka/nft-app',
		id: 8,
	},
	{
		title: 'Showcase Chat App',
		description: "",
		image: '/images/10.jpg',
		tags: ['React-Native', "Firebase", "GiftedChat", 'Styled Component'],
		source: 'https://curly-boat-0775.on.fleek.co/',
		visit: 'https://github.com/Lyshka/chat-app',
		id: 9,
	},
	{
		title: 'Showcase Weather App',
		description: "",
		image: '/images/11.jpg',
		tags: ['React-Native', "JSON Api", 'Styled Component'],
		source: 'https://lingering-cherry-5516.on.fleek.co/',
		visit: 'https://github.com/Lyshka/weatherApp',
		id: 10,
	},
	{
		title: 'Showcase Player App',
		description: "",
		image: '/images/12.jpg',
		tags: ['React-Native', "Media Library", 'Styled Component'],
		source: 'https://square-unit-8848.on.fleek.co/',
		visit: 'https://github.com/Lyshka/player-app',
		id: 11,
	},
	{
		title: 'Showcase Todo App',
		description: "",
		image: '/images/13.jpg',
		tags: ['React-Native', "Firebase", 'Styled Component'],
		source: 'https://plain-bar-6885.on.fleek.co/',
		visit: 'https://github.com/Lyshka/todo-app',
		id: 12,
	},
];

export const TimeLineData = [
	{year: 2021, text: 'Started my journey', },
	{year: 2022, text: 'Studied new technologies and created new ped projects', },
];